#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jforsstr <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/02/22 14:47:38 by jforsstr          #+#    #+#              #
#    Updated: 2020/02/22 14:59:38 by jforsstr         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = colle-2
FUNCTIONS =
OFILES = 
INCLUDES = librush.a


all: 

Comp:
	gcc -Wall -Werror -Wextra $(NAME) -i $(INCLUDES)

fclean:
	rm -f $(NAME)
